import sys
import os
from random import randint
import time
import datetime


clients_number = 0
request_length = 0
if not len(sys.argv) == 3:
    print("Must be two parameters: clients per second and request length (text length)")
    print("Now clients number will be generated by random (from 1 to 200)")
    print("And request length will be also generated by random (from 10 to 5000)")
    clients_number = randint(1,200)
    request_length = randint(10,5000)
else:
    clients_number = int(sys.argv[1])
    request_length = int(sys.argv[2])


while (True):
    dt = datetime.datetime.now()
    curr_time = '%s:%s:%s' % (dt.hour, dt.minute, dt.second)
    print("Generated at %s" % curr_time)
    for i in range(0, clients_number):
        os.system("./client %d" % request_length)
    time.sleep(1)
